[package]
name = "uluru"
version = "0.1.0"
authors = ["The Servo Project Developers"]
license = "MPL-2.0"
description = "A simple, fast, LRU cache implementation"
repository = "https://github.com/servo/uluru"
keywords = ["cache", "linkedlist", "array"]
categories = ["data-structures"]
readme = "README.md"

[lib]
name = "uluru"
path = "lib.rs"

[dependencies]
arrayvec = "0.3.20"
